### ISSUE TITLE
headless build issue ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by bshowket** [javacoin84Bln/javacoin#1]
Trying to build from source with this command as documented
`make -f makefile.unix`
which giving me this error

> /javacoin/src/leveldb/util/options.cc:17: undefined reference to `leveldb::Env::Default()'
> collect2: error: ld returned 1 exit status
> makefile.unix:180: recipe for target 'javacoind' failed
> make: *** [javacoind] Error 1
>

**Comment by javacoin84Bln** [comment]
Please make sure that required libraries are installed. 
try installing Berkeley DB 4.8:
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8+±dev

In src folder
cd leveldb
chmod +x build_detect_platform
cd ..
make clean -f makefile.unix
